swsnu/swpp2020-team7

backend/naengpa/user/models.py, backend/naengpa/user/views.py, frontend/naengpa/src/App.tsx, frontend/naengpa/src/containers/Auth/Login/Login.scss, frontend/naengpa/src/containers/Auth/Login/Login.tsx, frontend/naengpa/src/containers/Auth/Logout/Logout.tsx, frontend/naengpa/src/containers/Auth/Signup/Signup.scss, frontend/naengpa/src/containers/Auth/Signup/Signup.tsx, frontend/naengpa/src/store/actions/index.ts, frontend/naengpa/src/store/actions/user.ts, frontend/naengpa/src/store/reducers/user.ts
1. user should login before using naengpa web application 
-> before login: redirected to login page 
-> after login: redirected to fridge page
2. login & logout & singup scss styling modified
3. backend 'no-self-argument' error
=> [Frontend][Backend] Auth scss styling modified & tried to solve pylint error

frontend/naengpa/src/components/Ingredient/Ingredient.tsx, frontend/naengpa/src/containers/Auth/Login/Login.scss, frontend/naengpa/src/containers/Auth/Signup/Signup.scss
* login & signup scss modified
=> [Frontend] login & signup scss modified

backend/naengpa/user/tests.py, frontend/naengpa/src/components/Navigation/Navigation.test.tsx
*  testing code for Navigation frontend
*  testing code for user backend
=> testing for user backend and Navigation frontend

backend/naengpa/ingredient/tests.py, backend/naengpa/recipe/tests.py, backend/naengpa/recipe/views.py, frontend/naengpa/src/components/Navigation/Navigation.test.tsx, frontend/naengpa/src/components/Recipe/Recipe.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.test.tsx, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.test.tsx, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.tsx, frontend/naengpa/src/containers/RecipeList/RecipeList.tsx, frontend/naengpa/src/model/recipe.ts, frontend/naengpa/src/setupTests.ts
**myfridge.tsx**
**ingredient & recipe views.py**
**frontend coverage**
**backend coverage**
=> [Frontend][Backend][Testing] test code for my fridge.tsx & recipe, ingredient backend test codes

backend/naengpa/article/views.py, backend/naengpa/food_category/management/commands/addfoodcategory.py, backend/naengpa/food_category/views.py, backend/naengpa/ingredient/views.py, backend/naengpa/ml/views.py, backend/naengpa/recipe/views.py, backend/naengpa/requirements.txt, backend/naengpa/user/views.py, backend/naengpa/utils/aws_utils.py, frontend/naengpa/src/containers/AddIngredient/AddIngredient.tsx, frontend/naengpa/src/containers/Auth/Signup/Signup.tsx, frontend/naengpa/src/containers/RegionalSetting/RegionalSetting.tsx, frontend/naengpa/src/store/actions/user.ts, frontend/naengpa/src/store/reducers/region.ts
- fixed lots of small errors occurring when merged
- refactored backend codes with decorators
- AddIngredient refactored, interactive search added
- signup/region-setting issues resolved
- s3 file upload issue solved
=> [Frontend][Backend] merge issues resolved, refactored backend apis, addingredient with search

backend/naengpa/user/urls.py, backend/naengpa/user/views.py, frontend/naengpa/src/containers/ArticleList/ArticleList.scss, frontend/naengpa/src/containers/ArticleList/CreateArticle/CreateArticle.scss, frontend/naengpa/src/containers/Mypage/ChangePassword/ChangePassword.scss, frontend/naengpa/src/containers/Mypage/ChangePassword/ChangePassword.tsx, frontend/naengpa/src/containers/Mypage/EditUserInfo/EditUserInfo.scss, frontend/naengpa/src/containers/Mypage/EditUserInfo/EditUserInfo.tsx, frontend/naengpa/src/containers/Mypage/UserInfo/UserInfo.tsx, frontend/naengpa/src/containers/RecipeList/RecipeList.tsx, frontend/naengpa/src/model/user.ts, frontend/naengpa/src/store/actions/actionTypes.ts, frontend/naengpa/src/store/actions/index.ts, frontend/naengpa/src/store/actions/user.ts, frontend/naengpa/src/store/reducers/user.ts
* change password
* article part scss fixed
=> [Frontend][Backend]change password implemented & minor scss fixed

frontend/naengpa/src/components/Ingredient/Ingredient.scss, frontend/naengpa/src/components/Ingredient/Ingredient.tsx, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.scss, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.tsx
modified Ingredient & TodayIngredient (due to FoodCategory revision)
=> [Frontend][Minor] modified Ingredient & TodayIngredient

backend/naengpa/article/views.py, backend/naengpa/user/views.py, frontend/naengpa/src/containers/ArticleList/CreateArticle/CreateArticle.scss, frontend/naengpa/src/containers/ArticleList/CreateArticle/CreateArticle.tsx, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.test.tsx
revised ArticleDetail & CreateArticle 
- now the user can only choose Article item from the user's ingredients in their fridge.
=> [Frontend][Backend] Article Feature Improved

backend/naengpa/recipe/views.py, frontend/naengpa/src/components/Navigation/Navigation.tsx, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.tsx, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.test.tsx, frontend/naengpa/src/store/actions/recipe.ts, frontend/naengpa/src/store/actions/user.ts
1. recipe create and extract ml feature bugs 
-> loading, not found ingredient, lost session, json.decode error 
-> toast used for error handling
2. missing username in url for mypage
=> [Frontend][Backend] create & extract ml feature all the bugs soleve 

frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.scss, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.tsx
=> [Frontend] Chat detail css fixed

backend/naengpa/recipe/models.py, backend/naengpa/requirements.txt, backend/naengpa/user/models.py, backend/naengpa/user/views.py, backend/naengpa/utils/aws_utils.py, backend/naengpa/utils/logmeal_utils.py, frontend/naengpa/src/containers/CreateComment/CreateComment.tsx, frontend/naengpa/src/store/actions/user.ts
- fixed wrong ** usages in cache.delete_many
- fixed missing related_names 'recipes'
- implemented png to jpeg conversion for logmeal utils
- implemented profile image upload
=> [Hotfix][Feat] fixed wrong ** usages and missing, implemented jpeg image conversion, profile image uploaded

frontend/naengpa/src/components/FeedLoading/FeedLoading.tsx, frontend/naengpa/src/containers/ArticleList/ArticleList.scss, frontend/naengpa/src/containers/ArticleList/ArticleList.tsx, frontend/naengpa/src/containers/RecipeList/RecipeList.scss, frontend/naengpa/src/containers/RecipeList/RecipeList.tsx, frontend/naengpa/src/containers/UserRecipe/UserRecipe.scss, frontend/naengpa/src/containers/UserRecipe/UserRecipe.tsx, frontend/naengpa/src/store/actions/actionTypes.ts, frontend/naengpa/src/store/actions/index.ts, frontend/naengpa/src/store/actions/recipe.ts, frontend/naengpa/src/store/reducers/recipe.ts
**frontend**
User Recipe Feature and Loading skeleton in recipe & article list
=> [Frontend] Loading for recipe & article list and User recipe implemented

backend/naengpa/article/views.py, frontend/naengpa/src/components/Article/Article.scss, frontend/naengpa/src/components/Article/Article.tsx, frontend/naengpa/src/components/Comment/Comment.scss, frontend/naengpa/src/components/Comment/Comment.tsx, frontend/naengpa/src/components/Recipe/Recipe.scss, frontend/naengpa/src/components/Recipe/Recipe.tsx, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.scss, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.tsx, frontend/naengpa/src/containers/CreateComment/CreateComment.scss, frontend/naengpa/src/containers/Fridge/Fridge.scss, frontend/naengpa/src/containers/MyFridge/MyFridge.scss, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.scss, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.tsx, frontend/naengpa/src/model/article.ts
- Article, Recipe, Comment, ArticleDetail, RecipeDetail scss improvement
=> [Frontend][Backend] Article, Recipe, Comment, ArticleDetail, RecipeDetail scss 

frontend/naengpa/src/containers/RegionalSetting/RegionalSetting.scss
=> [Frontend] regional setting css fixed

backend/naengpa/article/models.py, backend/naengpa/user/models.py, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.tsx, frontend/naengpa/src/containers/ArticleList/ArticleList.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.tsx, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.tsx
- detail pages image resized to 250x250
- article delete cache
- article detail data load process refactored
=> [Frontend] Article detail refactored

frontend/naengpa/src/components/Ingredient/Ingredient.tsx, frontend/naengpa/src/components/Recipe/Recipe.scss, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.scss, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.tsx, frontend/naengpa/src/containers/AddIngredient/AddIngredient.scss, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.scss, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.tsx, frontend/naengpa/src/containers/Fridge/Fridge.scss, frontend/naengpa/src/containers/Fridge/Fridge.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.scss, frontend/naengpa/src/containers/MyFridge/MyFridge.tsx, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.scss, frontend/naengpa/src/containers/UserRecipe/UserRecipe.tsx
=> [Frontend] MyFridge &Recipe scss

frontend/naengpa/src/components/Ingredient/Ingredient.scss, frontend/naengpa/src/components/Recipe/Recipe.scss, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.scss, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.tsx, frontend/naengpa/src/components/TodayRecipe/TodayRecipe.scss, frontend/naengpa/src/containers/AddIngredient/AddIngredient.scss, frontend/naengpa/src/containers/Fridge/Fridge.scss, frontend/naengpa/src/containers/MyFridge/MyFridge.scss
- MyFridge Page scss improvement
=> [Frontend] MyFridge Page scss improvement

frontend/naengpa/src/components/Tab/Tab.tsx, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.scss, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.scss, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.tsx, frontend/naengpa/src/containers/Mypage/EditUserInfo/EditUserInfo.scss, frontend/naengpa/src/containers/Mypage/UserNotification/UserNotification.scss, frontend/naengpa/src/containers/UserRecipe/UserRecipe.scss, frontend/naengpa/src/containers/UserRecipe/UserRecipe.tsx
* overall design of my page is fixed
=> [Frontend] My page design fixed

backend/naengpa/article/views.py, frontend/naengpa/src/components/RecipeModal/NewIngredient/NewIngredient.tsx, frontend/naengpa/src/containers/ArticleList/ArticleList.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.tsx, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.scss, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.tsx, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.scss, frontend/naengpa/src/containers/RecipeList/RecipeList.scss
**Frontend**
Extract ml page add ingredient bug 
chat deatil username to name,
article query option modified
=> [Frontend] Extract ml page, chat detail username, article query, add ingredient

frontend/naengpa/src/components/Recipe/Recipe.scss, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.scss, frontend/naengpa/src/components/TodayRecipe/TodayRecipe.scss, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.scss, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.tsx, frontend/naengpa/src/containers/Fridge/Fridge.scss, frontend/naengpa/src/containers/Fridge/Fridge.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.scss, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.scss, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.tsx
- MyFridge scss improvement & ArticleDetail, RecipeDetail minor changes
=> [Frontend] MyFridge scss improvement & ArticleDetail, RecipeDetail minor changes

frontend/naengpa/src/components/Recipe/Recipe.scss, frontend/naengpa/src/components/RecipeModal/NewIngredient/NewIngredient.tsx, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.scss, frontend/naengpa/src/containers/AddIngredient/AddIngredient.scss, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.tsx, frontend/naengpa/src/containers/Fridge/Fridge.scss, frontend/naengpa/src/containers/MyFridge/MyFridge.scss, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.tsx
=> [Frontend] Minor scss changes

frontend/naengpa/src/components/RecipeModal/NewIngredient/NewIngredient.tsx, frontend/naengpa/src/components/Tab/Tab.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.scss, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.tsx
*  minor design fixed & lint error fixed
=> [Frontend] minor design fixed & lint error fixed

frontend/naengpa/src/components/Navigation/Navigation.test.tsx, frontend/naengpa/src/components/Recipe/Recipe.test.tsx, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.test.tsx, frontend/naengpa/src/containers/ArticleList/ArticleList.tsx, frontend/naengpa/src/containers/Auth/Login/Login.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.tsx, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.test.tsx, frontend/naengpa/src/containers/Fridge/Fridge.test.tsx, frontend/naengpa/src/containers/Fridge/Fridge.tsx, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.test.tsx, frontend/naengpa/src/store/actions/article.test.tsx, frontend/naengpa/src/store/reducers/user.test.tsx
=> [Tesing] fix testing error

frontend/naengpa/src/components/Tab/Tab.tsx, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.test.tsx, frontend/naengpa/src/components/TodayIngredient/TodayIngredient.tsx, frontend/naengpa/src/containers/Auth/Login/Login.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.tsx, frontend/naengpa/src/containers/Fridge/Fridge.test.tsx, frontend/naengpa/src/containers/Fridge/Fridge.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.test.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.tsx, frontend/naengpa/src/containers/RecipeList/RecipeList.tsx, frontend/naengpa/src/containers/RegionalSetting/RegionalSetting.tsx
**Frontend Bugs**
1. ingredient list is not updated -> added loading for 'today ingredient' & 'fridge' component
2. chatdetail polling issue solved
2. chatdetail tab color fixed
=> [Frontend] My Fridge Ingredient  List not loaded issue, ChatRoom polling issue etc solved

backend/naengpa/article/views.py, backend/naengpa/utils/logmeal_utils.py, frontend/naengpa/src/components/Article/Article.tsx, frontend/naengpa/src/components/RecipeModal/FoodCategoryModal/FoodCategoryModal.test.tsx, frontend/naengpa/src/components/RecipeModal/IngredientListModal/IngredientListModal.test.tsx, frontend/naengpa/src/components/RecipeModal/MLFeatureAlert/MLFeatureAlert.test.tsx, frontend/naengpa/src/components/RecipeModal/NewIngredient/NewIngredient.test.tsx, frontend/naengpa/src/components/RecipeModal/NewIngredient/NewIngredient.tsx, frontend/naengpa/src/components/Tab/Tab.test.tsx, frontend/naengpa/src/components/Tab/Tab.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.tsx, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.tsx, frontend/naengpa/src/containers/Mypage/ChangePassword/ChangePassword.test.tsx, frontend/naengpa/src/containers/Mypage/EditUserInfo/EditUserInfo.test.tsx, frontend/naengpa/src/containers/Mypage/UserNotification/UserNotification.tsx, frontend/naengpa/src/containers/RecipeList/RecipeList.tsx, frontend/naengpa/src/containers/RegionalSetting/RegionalSetting.test.tsx, frontend/naengpa/src/containers/RegionalSetting/RegionalSetting.tsx, frontend/naengpa/src/containers/UserRecipe/UserRecipe.test.tsx, frontend/naengpa/src/store/actions/article.ts, frontend/naengpa/src/store/reducers/fridge.test.tsx, frontend/naengpa/src/store/reducers/recipe.ts
=> [Testing] testing completed for 10+ frontend components, code smells fixed

frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.test.tsx, frontend/naengpa/src/containers/ArticleList/ArticleDetail/ArticleDetail.tsx, frontend/naengpa/src/containers/ArticleList/CreateArticle/CreateArticle.test.tsx, frontend/naengpa/src/containers/ArticleList/CreateArticle/CreateArticle.tsx, frontend/naengpa/src/containers/ArticleList/EditArticle/EditArticle.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.test.tsx, frontend/naengpa/src/containers/CreateComment/CreateComment.test.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.test.tsx, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.test.tsx, frontend/naengpa/src/containers/RecipeList/RecipeDetail/RecipeDetail.tsx, frontend/naengpa/src/containers/RecipeList/RecipeList.test.tsx
=> [Frontend][Test] CreateComment, Article detail & edit, Recipe deatail & list and part of ChatroomList & ChatDetail 

frontend/naengpa/src/components/Tab/Tab.tsx, frontend/naengpa/src/containers/Auth/Signup/Signup.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatDetail/ChatDetail.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.test.tsx, frontend/naengpa/src/containers/ChatRoomList/ChatRoomList.tsx, frontend/naengpa/src/containers/MyFridge/MyFridge.test.tsx
=> [Testing] Frontend testing for Tab, Signup, ChatRoomList, ChatRoomDetail, MyFridge

frontend/naengpa/src/containers/ArticleList/CreateArticle/CreateArticle.test.tsx, frontend/naengpa/src/containers/ExtractMLFeature/ExtractMLFeature.test.tsx, frontend/naengpa/src/containers/Fridge/Fridge.test.tsx, frontend/naengpa/src/containers/Fridge/Fridge.tsx, frontend/naengpa/src/containers/RecipeList/CreateRecipe/CreateRecipe.test.tsx
=> [Frontend][Testing] Fridge & article, recipe tried
